from __future__ import annotations

from pathlib import Path

from app.core.config import settings
from app.models import Scenario, Unit


def afsim_available() -> dict[str, str | bool]:
    bin_dir = settings.afsim_root / "bin"
    return {
        "root": str(settings.afsim_root),
        "exists": settings.afsim_root.exists(),
        "bin_exists": bin_dir.exists(),
        "warlock": str(bin_dir / "warlock.exe"),
        "wsf_runner": str(bin_dir / "wsf_runner.exe"),
    }


def _platform_block(unit: Unit) -> str:
    lat = 35.0 + unit.position.y / 110.0
    lon = 120.0 + unit.position.x / 90.0
    return f"""platform {unit.id} {unit.kind}
   side {unit.side}
   position {lat:.6f} deg {lon:.6f} deg altitude {unit.altitude_km:.3f} km
   heading {unit.heading_deg:.2f} deg
   speed {unit.speed_kps:.3f} km/s
end_platform
"""


def export_scenario_draft(scenario: Scenario, output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"{scenario.id}.afsim.txt"
    lines = [
        "# AFSIM draft generated by AFSIM_LLM",
        "# This is an integration skeleton for manual validation against local AFSIM grammar.",
        f"# Scenario: {scenario.name}",
        f"# Domain: {scenario.domain}, terrain={scenario.terrain}, weather={scenario.weather}",
        "",
    ]
    lines.extend(_platform_block(unit) for unit in scenario.units)
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
