from __future__ import annotations

import json
import math
import re
import time
from pathlib import Path
from typing import Any

from app.core.config import PROJECT_ROOT
from app.models import AFSimRoutePoint, AFSimScenarioDesign


GENERATED_ROOT = PROJECT_ROOT / "generated_scenarios"
DEFAULT_INPUT_FILE = "scenario.txt"


def _safe_name(name: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_\-]+", "_", name.strip())
    return cleaned[:80] or "web_scenario"


def _format_coord(value: float, positive: str, negative: str) -> str:
    hemi = positive if value >= 0 else negative
    return f"{abs(value):.6f}{hemi}"


def _platform_type_block() -> list[str]:
    return [
        "platform_type WEB_AIRCRAFT WSF_PLATFORM",
        "   icon F-22",
        "   category aircraft",
        "   mover WSF_AIR_MOVER",
        "      roll_rate_limit 1 rad/sec",
        "      default_linear_acceleration 1.0 g",
        "      default_radial_acceleration 4.0 g",
        "      default_climb_rate 300 fps",
        "      maximum_speed 900 knots",
        "      maximum_altitude 60000 ft",
        "      minimum_altitude 0 ft",
        "      at_end_of_path extrapolate",
        "   end_mover",
        "end_platform_type",
        "",
    ]


def _auto_end_point(platform: Any, end_time_seconds: int) -> AFSimRoutePoint:
    seconds = min(max(end_time_seconds, 60), 900)
    distance_nm = platform.speed_kts * seconds / 3600.0
    heading_rad = math.radians(platform.heading_deg)
    delta_lat = math.cos(heading_rad) * distance_nm / 60.0
    cos_lat = max(math.cos(math.radians(platform.lat)), 0.05)
    delta_lon = math.sin(heading_rad) * distance_nm / (60.0 * cos_lat)
    return AFSimRoutePoint(
        lat=max(min(platform.lat + delta_lat, 89.9), -89.9),
        lon=max(min(platform.lon + delta_lon, 179.9), -179.9),
        altitude_m=platform.altitude_m,
        speed_kts=platform.speed_kts,
    )


def _route_points(platform: Any, end_time_seconds: int) -> list[AFSimRoutePoint]:
    start = AFSimRoutePoint(
        lat=platform.lat,
        lon=platform.lon,
        altitude_m=platform.altitude_m,
        speed_kts=platform.speed_kts,
    )
    points = [start]
    for point in platform.route:
        if abs(point.lat - start.lat) < 0.000001 and abs(point.lon - start.lon) < 0.000001:
            continue
        points.append(point)
    if len(points) < 2:
        points.append(_auto_end_point(platform, end_time_seconds))
    return points


def _safe_generated_dir(scenario_id: str) -> Path:
    if not re.fullmatch(r"[A-Za-z0-9_\-]+", scenario_id):
        raise ValueError(f"invalid scenario_id: {scenario_id}")
    scenario_dir = (GENERATED_ROOT / scenario_id).resolve()
    root = GENERATED_ROOT.resolve()
    if root not in scenario_dir.parents and scenario_dir != root:
        raise ValueError("scenario path escaped generated root")
    return scenario_dir


def generate_scenario(design: AFSimScenarioDesign) -> dict[str, Any]:
    if not design.platforms:
        raise ValueError("scenario design must contain at least one platform")
    scenario_id = f"{int(time.time())}_{_safe_name(design.name)}"
    scenario_dir = GENERATED_ROOT / scenario_id
    output_dir = scenario_dir / "output"
    scenario_dir.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(exist_ok=True)

    lines = [
        "# Generated by AFSIM_LLM Web Scenario Designer",
        f"# Scenario: {design.name}",
        f"# Description: {design.description}",
        "file_path .",
        "",
        f"log_file output/{scenario_id}.log",
        f"event_output file output/{scenario_id}.evt end_event_output",
        f"event_pipe file output/{scenario_id}.aer end_event_pipe",
        "",
    ]
    lines.extend(_platform_type_block())

    used_names: set[str] = set()
    for platform in design.platforms:
        platform_name = _safe_name(platform.name)
        while platform_name in used_names:
            platform_name = f"{platform_name}_1"
        used_names.add(platform_name)
        type_name = _safe_name(platform.type_name).upper()
        if type_name in {"WSF_PLATFORM", "WEB", "WEB_PLATFORM", "WEB_AIRCRAFT", "AIRCRAFT"}:
            type_name = "WEB_AIRCRAFT"
        lines.extend(
            [
                f"platform {platform_name} {type_name}",
                f"   side {platform.side}",
                f"   category {platform.category}",
                f"   icon {platform.icon}",
                "   route",
            ]
        )
        for point in _route_points(platform, design.end_time_seconds):
            lat = _format_coord(point.lat, "n", "s")
            lon = _format_coord(point.lon, "e", "w")
            lines.extend(
                [
                    f"      position {lat} {lon} altitude {point.altitude_m:.1f} m msl",
                    f"         speed {point.speed_kts:.1f} kts",
                ]
            )
        lines.extend(["   end_route", f"   heading {platform.heading_deg:.1f} deg", "end_platform", ""])
    lines.append(f"end_time {design.end_time_seconds} sec")
    scenario_path = scenario_dir / DEFAULT_INPUT_FILE
    scenario_path.write_text("\n".join(lines), encoding="utf-8")
    (scenario_dir / "design.json").write_text(design.model_dump_json(indent=2), encoding="utf-8")
    return {
        "scenario_id": scenario_id,
        "scenario_dir": str(scenario_dir),
        "input_file": DEFAULT_INPUT_FILE,
        "scenario_path": str(scenario_path),
        "design": json.loads(design.model_dump_json()),
    }


def list_generated_scenarios(limit: int = 100) -> list[dict[str, Any]]:
    if not GENERATED_ROOT.exists():
        return []
    rows: list[dict[str, Any]] = []
    for design_path in sorted(GENERATED_ROOT.glob("*/design.json"), key=lambda p: p.stat().st_mtime, reverse=True)[:limit]:
        scenario_dir = design_path.parent
        scenario_path = scenario_dir / DEFAULT_INPUT_FILE
        try:
            design = json.loads(design_path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        rows.append(
            {
                "scenario_id": scenario_dir.name,
                "name": design.get("name", scenario_dir.name),
                "description": design.get("description", ""),
                "platform_count": len(design.get("platforms", [])),
                "end_time_seconds": design.get("end_time_seconds"),
                "scenario_dir": str(scenario_dir),
                "scenario_path": str(scenario_path),
                "input_file": DEFAULT_INPUT_FILE,
                "modified": design_path.stat().st_mtime,
                "exists": scenario_path.exists(),
            }
        )
    return rows


def read_generated_scenario(scenario_id: str) -> dict[str, Any]:
    scenario_dir = _safe_generated_dir(scenario_id)
    design_path = scenario_dir / "design.json"
    scenario_path = scenario_dir / DEFAULT_INPUT_FILE
    if not design_path.exists() or not scenario_path.exists():
        raise FileNotFoundError(f"generated scenario not found: {scenario_id}")
    return {
        "scenario_id": scenario_id,
        "scenario_dir": str(scenario_dir),
        "scenario_path": str(scenario_path),
        "input_file": DEFAULT_INPUT_FILE,
        "design": json.loads(design_path.read_text(encoding="utf-8")),
        "scenario_text": scenario_path.read_text(encoding="utf-8", errors="ignore"),
    }


def generated_input_path(scenario_id: str) -> Path:
    scenario_dir = _safe_generated_dir(scenario_id)
    scenario_path = scenario_dir / DEFAULT_INPUT_FILE
    if not scenario_path.exists():
        raise FileNotFoundError(f"generated scenario input not found: {scenario_id}")
    return scenario_path
